//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Errlock.Resources.ModulesData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PasswordCrackerData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PasswordCrackerData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Errlock.Resources.ModulesData.PasswordCrackerData", typeof(PasswordCrackerData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password
        ///123456
        ///12345678
        ///1234
        ///qwerty
        ///12345
        ///dragon
        ///pussy
        ///baseball
        ///football
        ///letmein
        ///monkey
        ///696969
        ///abc123
        ///mustang
        ///michael
        ///shadow
        ///master
        ///jennifer
        ///111111
        ///2000
        ///jordan
        ///superman
        ///harley
        ///1234567
        ///fuckme
        ///hunter
        ///fuckyou
        ///trustno1
        ///ranger
        ///buster
        ///thomas
        ///tigger
        ///robert
        ///soccer
        ///fuck
        ///batman
        ///test
        ///pass
        ///killer
        ///hockey
        ///george
        ///charlie
        ///andrew
        ///michelle
        ///love
        ///sunshine
        ///jessica
        ///asshole
        ///6969
        ///pepper
        ///daniel
        ///access
        ///123456789
        ///654321
        ///joshua
        ///maggie
        ///starwars
        ///silver
        ///william
        ///dallas
        ///yankees        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Passwords {
            get {
                return ResourceManager.GetString("Passwords", resourceCulture);
            }
        }
    }
}
