//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Errlock.Resources.ModulesData {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class PublicFinderData {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PublicFinderData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Errlock.Resources.ModulesData.PublicFinderData", typeof(PublicFinderData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pub
        ///public
        ///publ
        ///global
        ///data
        ///static.
        /// </summary>
        public static string Data0 {
            get {
                return ResourceManager.GetString("Data0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bibl
        ///secret
        ///photos
        ///photo
        ///images
        ///ref
        ///pic
        ///pics
        ///pictures
        ///picture
        ///log
        ///logs
        ///img.
        /// </summary>
        public static string Data1 {
            get {
                return ResourceManager.GetString("Data1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .svn
        ///.git
        ///admin.
        /// </summary>
        public static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -
        ///_
        ///+
        ///%20.
        /// </summary>
        public static string Separators {
            get {
                return ResourceManager.GetString("Separators", resourceCulture);
            }
        }
    }
}
