//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Errlock.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NoticeDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NoticeDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Errlock.Resources.NoticeDescriptions", typeof(NoticeDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использутеся веб-сервер, который не предназначен для работы в продакшене. Использование таких серверов может очень сильно замедлять работу приложения, не иметь средств для тонкой настройки своей работы и иметь проблемы безопасности. Рекомендуется использовать известные веб-сервера, если данный сайт работает в продкшене..
        /// </summary>
        public static string NonProductionServerNotice {
            get {
                return ResourceManager.GetString("NonProductionServerNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер ответил с кодом 200, и это обычно означает, что доступ к данному ресурсу неограничен. Возможно, что при переходе по данной ссылке, веб-сервер отдает список файлов (что обычно нежелательно). Рекомендуется проверить данную страницу, и при необходимости ограничить доступ анонимных пользователей к ней..
        /// </summary>
        public static string OpenResource {
            get {
                return ResourceManager.GetString("OpenResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о сервера может быть полезна в случаях, когда используемая версия веб-сервера может быть уязивима..
        /// </summary>
        public static string ServerInfo {
            get {
                return ResourceManager.GetString("ServerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер ответил с кодом 401 при попытке загрузить страницу. Для доступа к данному ресурсу требуется авторизация. Возможно, что авторизация не настроена должным образом, и злоумышленник может получить доступ к системе (например при небезопасном пароле)..
        /// </summary>
        public static string SuspiciousUrl401 {
            get {
                return ResourceManager.GetString("SuspiciousUrl401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер ответил с кодом 403 при попытке загрузить страницу. Обычно это нормальное поведение, но иногда такие страницы могут отображать приватный контент, несмотря на ошибку доступа..
        /// </summary>
        public static string SuspiciousUrl403 {
            get {
                return ResourceManager.GetString("SuspiciousUrl403", resourceCulture);
            }
        }
    }
}
